sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite2, otherSprite2) {
    game.gameOver(true)
})
game.showLongText("Welcome to my game!", DialogLayout.Bottom)
pause(100)
game.showLongText("You are in a small room, and there is no escape. Stay alive for 25 seconds to defeat the beast. If the beast runs into you, the game ends... ", DialogLayout.Bottom)
pause(100)
game.showLongText("Ready?", DialogLayout.Bottom)
pause(100)
let NewSprite = sprites.create(assets.image`Hero`, SpriteKind.Player)
controller.moveSprite(NewSprite)
NewSprite.setStayInScreen(true)
let EvilPerson1 = sprites.create(assets.image`EvilPerson`, SpriteKind.Enemy)
let EvilPerson2 = sprites.create(assets.image`EvilPerson`, SpriteKind.Enemy)
EvilPerson1.x = randint(10, 150)
EvilPerson1.y = randint(10, 80)
EvilPerson1.x = randint(10, 80)
EvilPerson2.y = randint(10, 80)
EvilPerson1.follow(NewSprite, 60)
EvilPerson2.follow(NewSprite, 60)
